global using Materal.Abstractions;
global using Materal.Extensions;
global using Materal.Extensions.DependencyInjection;
global using Materal.MergeBlock.Abstractions.Models;
global using Materal.Utils;
global using Materal.Utils.Model;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using System.ComponentModel.DataAnnotations;
