// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MateralToolsVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "MateralToolsVSIX.332cc8a2-9065-4eac-b73a-62cc5596458f";
        public const string Name = "MateralToolsVSIX";
        public const string Description = @"Materal工具扩展";
        public const string Language = "zh-CN";
        public const string Version = "1.2.2";
        public const string Author = "Materal";
        public const string Tags = "";
    }
}
