// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MateralToolsVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "MateralToolsVSIX.76483ff7-1749-4014-9007-82c3a64b7cf3";
        public const string Name = "MateralToolsVSIX";
        public const string Description = @"MateralTools扩展";
        public const string Language = "zh-CN";
        public const string Version = "1.1.77.1";
        public const string Author = "陈明旭";
        public const string Tags = "";
    }
}
