// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MateralToolsVSIX
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MateralToolsVSIXString = "a8145487-f682-4352-b2c8-345bec8ec476";
        public static Guid MateralToolsVSIX = new Guid(MateralToolsVSIXString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SolutionMenuGroup = 0x0001;
        public const int ProjectMenuGroup = 0x0002;
        public const int PackagesPropsMenuGroup = 0x0003;
        public const int SolutionClearCommand = 0x0101;
        public const int ProjectClearCommand = 0x0102;
        public const int SortPackagesPropsCommand = 0x0103;
        public const int MateralToolCommand = 0x0111;
    }
}
