// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MateralMergeBlockVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MateralMergeBlockVSIXString = "98128b0e-7190-4626-8342-4a542c4a488d";
        public static Guid MateralMergeBlockVSIX = new Guid(MateralMergeBlockVSIXString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowManagerWindowCommand = 0x0100;
    }
}