// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectClear
{
    internal sealed partial class Vsix
    {
        public const string Id = "ProjectClear.c9d8abe9-3ce1-4ec3-bee9-80af0479bfdf";
        public const string Name = "ProjectClear";
        public const string Description = @"清理解决方案";
        public const string Language = "zh-CN";
        public const string Version = "1.1.76.1";
        public const string Author = "陈明旭";
        public const string Tags = "";
    }
}
