// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RC.EnvironmentServer.Repository;

#nullable disable

namespace RC.EnvironmentServer.Repository.Migrations
{
    [DbContext(typeof(EnvironmentServerDBContext))]
    partial class EnvironmentServerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("RC.EnvironmentServer.Domain.ConfigurationItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("描述");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("键");

                    b.Property<Guid>("NamespaceID")
                        .HasColumnType("TEXT")
                        .HasComment("命名空间唯一标识");

                    b.Property<string>("NamespaceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("命名空间名称");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("TEXT")
                        .HasComment("项目唯一标识");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("项目名称");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("值");

                    b.HasKey("ID");

                    b.ToTable("ConfigurationItem", t =>
                        {
                            t.HasComment("配置项");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
