/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AutoNodeHandleData: typeof import('./src/components/AutoNodeHandleData.vue')['default']
    ConsoleMessageAutoNode: typeof import('./src/components/AutoNodes/ConsoleMessageAutoNode.vue')['default']
    copy: typeof import('./src/components/DataTypeEnumSelect copy.vue')['default']
    DataModelFieldList: typeof import('./src/components/DataModelFieldList.vue')['default']
    DataModelFieldOption: typeof import('./src/components/DataModelFieldOption.vue')['default']
    DataModelList: typeof import('./src/components/DataModelList.vue')['default']
    DataModelOption: typeof import('./src/components/DataModelOption.vue')['default']
    DataTypeEnumSelect: typeof import('./src/components/DataTypeEnumSelect.vue')['default']
    FlowTemplateCanvas: typeof import('./src/components/FlowTemplateCanvas.vue')['default']
    FlowTemplateList: typeof import('./src/components/FlowTemplateList.vue')['default']
    FlowTemplateOption: typeof import('./src/components/FlowTemplateOption.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    InitiatorNodeHandleData: typeof import('./src/components/InitiatorNodeHandleData.vue')['default']
    NodeHandleTypeEnumSelect: typeof import('./src/components/NodeHandleTypeEnumSelect.vue')['default']
    NodeItem: typeof import('./src/components/NodeItem.vue')['default']
    NodeOption: typeof import('./src/components/NodeOption.vue')['default']
    PageTemplateOption: typeof import('./src/components/PageTemplateOption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepOption: typeof import('./src/components/StepOption.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    UserNodeHandleData: typeof import('./src/components/UserNodeHandleData.vue')['default']
    UserOption: typeof import('./src/components/UserOption.vue')['default']
  }
}
