//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using RC.Demo.RepositoryImpl;

//#nullable disable

//namespace RC.Demo.Migrations
//{
//    [DbContext(typeof(DemoDBContext))]
//    partial class DemoDBContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

//            modelBuilder.Entity("RC.Demo.Domain.User", b =>
//                {
//                    b.Property<Guid>("ID")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("TEXT");

//                    b.Property<DateTime>("CreateTime")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("TEXT");

//                    b.Property<byte>("Sex")
//                        .HasColumnType("INTEGER");

//                    b.Property<DateTime>("TestTime")
//                        .HasColumnType("TEXT");

//                    b.Property<DateTime>("UpdateTime")
//                        .HasColumnType("TEXT");

//                    b.HasKey("ID");

//                    b.ToTable("User");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
