// <auto-generated />
using System;
using Materal.TTA.Demo.SqlServerEFRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Materal.TTA.Demo.SqlServerEFRepository.Migrations
{
    [DbContext(typeof(TTADemoDBContext))]
    [Migration("20230427093548_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Materal.TTA.Demo.Domain.TestDomain", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ByteType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateTimeType")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DecimalType")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("EnumType")
                        .HasColumnType("tinyint");

                    b.Property<int>("IntType")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("StringType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TestDomain");
                });
#pragma warning restore 612, 618
        }
    }
}
