global using Materal.Abstractions;
global using Materal.Extensions;
global using Materal.Extensions.Models;
global using Microsoft.Extensions.Configuration;
global using System.Collections;
global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Text;
