// <auto-generated />
using System;
using Materal.Oscillator.LocalDR;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Materal.Oscillator.LocalDR.Migrations
{
    [DbContext(typeof(OscillatorLocalDRDBContext))]
    [Migration("20221212063147_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Materal.Oscillator.DR.Domain.Flow", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthenticationCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScheduleID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkID")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkResults")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Flow");
                });
#pragma warning restore 612, 618
        }
    }
}
