// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MateralMergeBlockVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "MateralMergeBlockVSIX.b1552ba8-4727-4fcf-8258-ef4040604f52";
        public const string Name = "MateralMergeBlockVSIX";
        public const string Description = @"Materal.MergeBlock项目专用插件";
        public const string Language = "zh-Hans";
        public const string Version = "1.1.77.6";
        public const string Author = "Materal";
        public const string Tags = "Materal.MergeBlock";
    }
}
