// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MateralMergeBlockVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "MateralMergeBlockVSIX.8759d170-31fb-4d6d-a35f-94f7586a0eb4";
        public const string Name = "MateralMergeBlockVSIX";
        public const string Description = @"Materal.MergeBlock项目专用插件";
        public const string Language = "zh-CN";
        public const string Version = "1.2.6";
        public const string Author = "Materal";
        public const string Tags = "";
    }
}
