global using Materal.Abstractions;
global using Materal.Extensions;
global using Materal.Utils.Http;
global using Materal.Utils.Model;
global using Materal.Utils.Wechat.Model.Event;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Text;
global using System.Xml;
